### ISSUE TITLE
Show value instead of percent for non-mana power

### ISSUE THREAD

**Issue by frumpymoons** [phanx-wow/oUF_Phanx#16]
The rage text shows a wrong number. (Maybe on other classes too, I play only warrior atm)

In the screenshot I have 18 rage points according to oUF_Phanx and 20 according to nPower.
My skill on hotkey 4 needs 20 or more and I am able to cast it. So nPower shows the wright number.

![wowscrnshot_090116_001801](https://cloud.githubusercontent.com/assets/551155/18148509/46fd1772-6fda-11e6-9444-63c5a05907f1.jpg)

**Comment by Phanx** [comment]
Not sure what to tell you. oUF_Phanx just queries the standard `UnitPower` API function, and displays whatever number the game client returns. If you notice such a discrepancy again, run this command and report back with what it says in your chat frame:

    /dump UnitPower("player")

Other than that, this could happen if something was causing an actual error (thus preventing the update function from completing) but I see a green BugSack icon in your screenshot (no errors) so that isn't happening here.

**Comment by frumpymoons** [comment]
/dump UnitPower("player") shows always a different number than the playerframe.
I found out that if I hover over the playerframe the correct number shows up :S

So I looked in the Functions.lua and change line 302 

from

`self.value:SetFormattedText("%d|cff%02x%02x%02x|r", floor(UnitPower(unit) / UnitPowerMax(unit) * 100 + 0.5), color[1] * 255, color[2] * 255, color[3] * 255)`

to

`self.value:SetFormattedText("%d|cff%02x%02x%02x|r", si(UnitPower(unit)), color[1] * 255, color[2] * 255, color[3] * 255)`

now the correct number shows all the time.

**Comment by Phanx** [comment]
Ah, I see where the confusion lies. The power text normally shows a %. In the past this was always the same as the current value for non-mana users, because the max value for rage/energy/focus was generally (if not always?) 100. It looks like you can now have up to 110 rage -- 20 / 110 = 18%, which is the 18 you were seeing (the actual % symbol was hidden) -- and some of the new non-mana power types have max values other than 100 too, so I should just switch those to show the current value instead of a percent.
